### ISSUE TITLE
Custom fonts?

### ISSUE THREAD

**Issue by mccpower** [fscz/html2pdf#1]
Hi, first of all thanks for sharing this module!.

I was wondering if there is a way to use custom fonts, I remember that you mentioned that it is not possible to pull resources and in the case of the images are encoded in base64 which I tested and works great but I am not sure if there is a way to use a custom font. 

What I have done is use a @font-face but of course it has a url reference to the resource itself so when I test my html it works fine but when I use the module the font is not working what makes sense for me based in the "problem" pulling resources.

Any help with this is very appreciated!

**Comment by sivanagak** [comment]
Can i use inline styles for html2pdf? if i use <strong>strong</strong> tag entire pdf is coming in strong.

**Comment by fscz** [comment]
Yes, you can. 

Gesendet von Mail für Windows 10

Von: sivanagak
Gesendet: Thursday, December 28, 2017 2:24 PM
An: fscz/html2pdf
Cc: fscz; Comment
Betreff: Re: [fscz/html2pdf] Custom fonts? (#1)

Can i use inline styles for html2pdf? if i use tag entire pdf is coming in strong.

**Comment by sivanagak** [comment]
if i use   `<p style="font-weight: bold;">testing.</p>` entire pdf is coming in bold.

**Comment by fscz** [comment]
Do you occasionally struggle being taken seriously as a dev? If so, consider providing code examples.

Gesendet von Mail für Windows 10

Von: sivanagak
Gesendet: Thursday, December 28, 2017 2:30 PM
An: fscz/html2pdf
Cc: fscz; Comment
Betreff: Re: [fscz/html2pdf] Custom fonts? (#1)

if i use 
Sivanaga
. entire pdf is coming in bold.

**Comment by sivanagak** [comment]
if i use this styles in my html code and send it to conversion as pdf.  `<p style="font-weight: bold;">testing.</p>` entire pdf is coming in bold. above paragraph tag is an example. do you need more code @fscz ?

**Comment by fscz** [comment]
I suspect that your html/css does not produce the overall result you intend. 

This module renders the webpage you specify in a UIWebView:
[webview loadHTMLString:html baseURL: nil];

And subsequently renders the UIWebView to a pdf using:
UIPrintPageRenderer *render = [[UIPrintPageRenderer alloc] init];
[render addPrintFormatter:webView.viewPrintFormatter startingAtPageAtIndex:0]; 
...

If the result is not, as you intend the underlying UIWebView does not produce the page, you think it produces, given your html string.
