### ISSUE TITLE
[iOS] pdfready not being fired on actual device

### ISSUE THREAD

**Issue by atypical** [fscz/html2pdf#4]
Firstly - great great work! Its exactly what I needed and I am modding it a bit to work with what I need.

It works perfectly in the simulator, however when I push the app onto a device, I see the pdfready event get fired in the (xcode) console, however nothing happens on the device. I threw a couple alerts within the html2pdf.addEventListener function - and they arent being fired when on the device.

I'm using the latest TiSDK and iOS 7 & 6.

Any help would be hugely appreciated.

If we can get this working, I got a couple pull requests I'm gonna send your way for a couple ideas.

Thank you!
MD

**Comment by caspahouzer** [comment]
I made a PR https://github.com/fscz/html2pdf/pull/7 which fixes the problem, that the event is not being fired on device. Also I upgraded the module to 64bit

**Comment by caspahouzer** [comment]
The newest build includes the functionality to set the filename. So I think this issue can be closed

**Comment by fscz** [comment]
use like so:
    
    var html = "<html>...</html>"
    module.setHtmlString([html, "filename.pdf"]) # pass an array now. 2nd arg is for filename
